name: Deploy to AWS S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.4.0

    - name: Use Node.js 20
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Start Node.js application
      run: npm start

    - name: Upload to S3 with Private Access
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        SOURCE_DIR: build/
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
