name: Deploy to AWS S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies (frontend)
      working-directory: app  # Update the directory name
      run: npm install

    - name: Build React app
      working-directory: app  # Update the directory name
      run: npm run build  # Assuming you have a build script for production

    - name: Install dependencies (backend)  # Optional if you have backend dependencies
      run: npm install  # Adjust if your backend build script is different

    - name: Build backend  # Optional if you have a separate backend build script
      run: npm run build:backend  # Adjust the command as needed

    - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
